[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.6"
chrono = "0.4"
sqlx = { version = "0.7.4", features = ["chrono", "macros", "postgres", "runtime-tokio-native-tls"] }
dotenv = "0.15"